language: generic
sudo: required
dist: trusty
services:
  - docker
before_install:
  - bin/before_install.sh
after_success:
  - bin/docker_push.sh
  - bin/kubernetes_deploy.sh
script: swift test
addons:
  apt:
    packages:
      - docker-ce
      - clang
      - libicu-dev
      - libpython2.7
notifications:
  email: false
