language: swift
osx_image: xcode10.1
sudo: required
services:
  - docker
after_success:
  - bin/docker_push.sh
  - bin/kubernetes_deploy.sh
script: swift test
addons:
  apt:
    packages:
      - docker-ce
notifications:
  email: false
