language: generic
sudo: required
dist: trusty
services:
  - docker
before_install:
  - bin/before_install.sh
after_success:
  - bin/docker_push.sh
  - bin/kubernetes_deploy.sh
script: swift test
addons:
  apt:
    packages:
      - libressl
      - docker-ce
notifications:
  email: false
