os: linux
language: generic
dist: trusty
sudo: required
services:
  - docker
after_success:
  - bin/docker_push.sh
  - bin/kubernetes_deploy.sh
script: echo "hello"
addons:
  apt:
    packages:
      - docker-ce
notifications:
  email: false
